name: React build
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: dcmsystem-v2   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'frontend/build'
  NODE_VERSION: '14.x'                # set this to the node version to use
  REACT_APP_ENCRYPT_KEY: ${{ secrets.REACT_APP_ENCRYPT_KEY }}
  REACT_APP_COSMOS_KEY: ${{ secrets.REACT_APP_COSMOS_KEY }}
  REACT_APP_ENDPOINT: ${{ secrets.REACT_APP_ENDPOINT }}
  CI: false
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@main
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install react-scripts --save
          npm install 
          npm run build --if-present
        working-directory: frontend
        env:
          REACT_APP_ENCRYPT_KEY: ${{ env.REACT_APP_ENCRYPT_KEY }}
          REACT_APP_COSMOS_KEY: ${{ env.REACT_APP_COSMOS_KEY }}
          REACT_APP_ENDPOINT: ${{ env.REACT_APP_ENDPOINT }}
        

      - name: Deploy                  # S3에 배포하기\
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
